### ISSUE TITLE
auto indentation doesn't work

### ISSUE THREAD

**Issue by gajendrajena** [ollykel/v-vim#3]
The syntax highlight works fine.
But indentation doesn't work.

**Comment by ravener** [comment]
Same here

**Comment by ernierasta** [comment]
Well, maybe it is because it is not implemented? ;-)

I also would like to see it working and, as with syntax highlighting, code can be taken from vim-go or other vim golang plugin. I will probably implement it if no one would do it, but it would be in distant future. So I hope someone would do it till then. ;-)
